[2024-11-22T15:00:40.387+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T15:00:40.480+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:00:03.571651+00:00 [queued]>
[2024-11-22T15:00:40.514+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:00:03.571651+00:00 [queued]>
[2024-11-22T15:00:40.514+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T15:00:40.615+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_task> on 2024-11-22 15:00:03.571651+00:00
[2024-11-22T15:00:40.697+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_etl_pipeline', 'transform_task', 'manual__2024-11-22T15:00:03.571651+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_extraction.py', '--cfg-path', '/tmp/tmp3vwo_wgy']
[2024-11-22T15:00:40.699+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask transform_task
[2024-11-22T15:00:40.686+0000] {logging_mixin.py:190} WARNING - /home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=35864) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T15:00:40.708+0000] {standard_task_runner.py:72} INFO - Started process 35997 to run task
[2024-11-22T15:00:41.047+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:00:03.571651+00:00 [running]> on host ubuntu
[2024-11-22T15:00:41.399+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team_14' AIRFLOW_CTX_DAG_ID='weather_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T15:00:03.571651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T15:00:03.571651+00:00'
[2024-11-22T15:00:41.400+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T15:00:41.400+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T15:00:41.401+0000] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-11-22 15:00:40.481837+00:00
[2024-11-22T15:00:41.401+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_etl_pipeline and current dag run status:running
[2024-11-22T15:00:41.401+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T15:00:41.446+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 78, in transform_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/vboxuser/airflow/weather-etl-pipeline/datasets/weather-history.csv'
[2024-11-22T15:00:41.520+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T15:00:41.520+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 15:00:40.481837+00:00 end:2024-11-22 15:00:41.519525+00:00 duration:1.037688
[2024-11-22T15:00:41.520+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: weather_data_etl_pipeline> dagrun:<DagRun weather_data_etl_pipeline @ 2024-11-22 15:00:03.571651+00:00: manual__2024-11-22T15:00:03.571651+00:00, state:running, queued_at: 2024-11-22 15:00:03.745836+00:00. externally triggered: True>
[2024-11-22T15:00:41.521+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/home/vboxuser/airflow/weather-etl-pipeline/datasets/weather-history.csv'
[2024-11-22T15:00:41.521+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_etl_pipeline, task_id=transform_task, run_id=manual__2024-11-22T15:00:03.571651+00:00, execution_date=20241122T150003, start_date=20241122T150040, end_date=20241122T150041
[2024-11-22T15:00:41.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T15:00:41.613+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task transform_task ([Errno 2] No such file or directory: '/home/vboxuser/airflow/weather-etl-pipeline/datasets/weather-history.csv'; 35997)
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 78, in transform_data
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/vboxuser/airflow/weather-etl-pipeline/datasets/weather-history.csv'
[2024-11-22T15:00:41.649+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T15:00:41.790+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:00:41.791+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
