[2024-11-22T15:34:23.640+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T15:34:23.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:32:05.500632+00:00 [queued]>
[2024-11-22T15:34:23.715+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:32:05.500632+00:00 [queued]>
[2024-11-22T15:34:23.730+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-22T15:34:23.802+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_task> on 2024-11-22 15:32:05.500632+00:00
[2024-11-22T15:34:23.817+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_etl_pipeline', 'transform_task', 'manual__2024-11-22T15:32:05.500632+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_extraction.py', '--cfg-path', '/tmp/tmpzymz2vr9']
[2024-11-22T15:34:23.830+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask transform_task
[2024-11-22T15:34:23.828+0000] {logging_mixin.py:190} WARNING - /home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=43462) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T15:34:23.844+0000] {standard_task_runner.py:72} INFO - Started process 43525 to run task
[2024-11-22T15:34:23.932+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_etl_pipeline.transform_task manual__2024-11-22T15:32:05.500632+00:00 [running]> on host ubuntu
[2024-11-22T15:34:24.058+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team_14' AIRFLOW_CTX_DAG_ID='weather_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T15:32:05.500632+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T15:32:05.500632+00:00'
[2024-11-22T15:34:24.064+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T15:34:24.064+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T15:34:24.065+0000] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-11-22 15:34:23.697717+00:00
[2024-11-22T15:34:24.065+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_etl_pipeline and current dag run status:running
[2024-11-22T15:34:24.065+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T15:34:38.780+0000] {logging_mixin.py:190} WARNING - /home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py:78 FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
[2024-11-22T15:34:38.793+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 81, in transform_data
    df['Month'] = df['Formatted Date'].dt.month
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/indexes/accessors.py", line 643, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2024-11-22T15:34:38.865+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T15:34:38.866+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 15:34:23.697717+00:00 end:2024-11-22 15:34:38.865116+00:00 duration:15.167399
[2024-11-22T15:34:38.866+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: weather_data_etl_pipeline> dagrun:<DagRun weather_data_etl_pipeline @ 2024-11-22 15:32:05.500632+00:00: manual__2024-11-22T15:32:05.500632+00:00, state:running, queued_at: 2024-11-22 15:32:05.641214+00:00. externally triggered: True>
[2024-11-22T15:34:38.866+0000] {logging_mixin.py:190} INFO - Failure caused by Can only use .dt accessor with datetimelike values
[2024-11-22T15:34:38.866+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_data_etl_pipeline, task_id=transform_task, run_id=manual__2024-11-22T15:32:05.500632+00:00, execution_date=20241122T153205, start_date=20241122T153423, end_date=20241122T153438
[2024-11-22T15:34:38.888+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T15:34:38.889+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task transform_task (Can only use .dt accessor with datetimelike values; 43525)
Traceback (most recent call last):
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/weather-etl-pipeline/dags/weather_data_extraction.py", line 81, in transform_data
    df['Month'] = df['Formatted Date'].dt.month
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/pandas/core/indexes/accessors.py", line 643, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2024-11-22T15:34:38.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T15:34:38.957+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:34:38.969+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
